import React, { useState, useEffect } from "react";
import {
  Mail,
  Plus,
  Search,
  Filter,
  Edit3,
  Eye,
  Copy,
  Trash2,
  Send,
  ChevronDown,
  X,
  Check,
  AlertCircle,
  Smartphone,
  Monitor,
  ArrowLeft,
} from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
// import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import { SUPABASE_PUBLISHABLE_KEY } from "@/integrations/supabase/client";
import Spinner from "../Spinner";
import { toast } from "sonner";

import ReactQuill from "react-quill";
import "react-quill/dist/quill.snow.css";

interface SupabaseEmailTemplate {
  id: string;
  template_name: string;
  description: string;
  type_email: string;
  status: "Active" | "Inactive";
  subject_Line: string;
  from_Name: string;
  from_Email: string;
  trigger: string;
  email_Footer?: string;
}

type NewSupabaseEmailTemplate = Omit<SupabaseEmailTemplate, "id"> & {
  id?: string;
};

export const SuperAdminEmail: React.FC = () => {
  const [view, setView] = useState<"list" | "editor" | "preview">("list");
  const [searchTerm, setSearchTerm] = useState("");
  const [filterStatus, setFilterStatus] = useState<
    "all" | "active" | "inactive"
  >("all");
  const [selectedTemplate, setSelectedTemplate] =
    useState<NewSupabaseEmailTemplate | null>(null);
  const [previewMode, setPreviewMode] = useState<"desktop" | "mobile">(
    "desktop"
  );
  const [showTestModal, setShowTestModal] = useState(false);
  const [testEmail, setTestEmail] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [autoSaved, setAutoSaved] = useState(false);

  const [dynamicTemplates, setDynamicTemplates] = useState<
    SupabaseEmailTemplate[]
  >([]);
  const [loading, setLoading] = useState(true);
  const [status, setStatus] = useState(true);
  const [AllTriggers, setAllTriggers] = useState([]);
  const [selectedTrigger, setSelectedTrigger] = useState("");
  const [editorContent, setEditorContent] = useState("");

  const [formData, setFormData] = useState({
    temp_name: "",
    subject_line: "",
    status: status === "active" ? true : false,
    triggers: "",
    footer: "",
    description: "",
    newTrigger: "",
  });

  useEffect(() => {
    fetchTemplates();
    fetchTriggers();
  }, []);

  const fetchTemplates = async () => {
    setLoading(true);
    const { data, error } = await supabase
      .from("email_template_table")
      .select("*");

    if (error) {
      console.error("Error fetching templates:", error);
      toast("Error while Fetching");
    } else {
      console.log("Fetched data:", data);
      setDynamicTemplates(data as SupabaseEmailTemplate[]);
    }
    setLoading(false);
  };

  const fetchTriggers = async () => {
    const { data, error } = await supabase
      .from("triggers")
      .select("id, trigger_name");

    if (error) {
      console.error("Error fetching triggers:", error);
    } else {
      // console.log("Data in triggers: ", data);
      setAllTriggers(data);
    }
  };

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  const filteredTemplates = dynamicTemplates.filter((template) => {
    const matchesSearch =
      template.template_name.toLowerCase().includes(searchTerm.toLowerCase()) ||
      template.description.toLowerCase().includes(searchTerm.toLowerCase());

    const matchesFilter =
      filterStatus === "all" ||
      (filterStatus === "active" && template.status === true) ||
      (filterStatus === "inactive" && template.status === false);

    return matchesSearch && matchesFilter;
  });

  const handleEditTemplate = (template: SupabaseEmailTemplate) => {
    setSelectedTemplate(template);
    console.log("Selected Template is :", template);
    setFormData({
      temp_name: template.template_name || "",
      subject_line: template.subject_Line || "",
      status: template.status,
      triggers: template.trigger || "",
      footer: template.email_Footer || "",
      description: template.description || "",
      newTrigger: template.trigger,
    });
    setEditorContent(template.description || "");

    console.log("Edit button Clicked: ", template);
    setView("editor");
  };

  const handleNewTemplate = () => {
    const newTemplate: NewSupabaseEmailTemplate = {
      // id is omitted here; it will be auto-generated by Supabase
      template_name: "New Template",
      description: "",
      type_email: "Manual",
      status: "Inactive",
      subject_Line: "",
      from_Name: "NovaFarm Team",
      from_Email: "noreply@novafarm.com",
      trigger: "manual",
      email_Footer:
        "<p>© 2024 NovaFarm. All rights reserved.</p><p>If you have any questions, please contact our support team.</p>",
    };
    setSelectedTemplate(newTemplate);
    setView("editor");
  };

  // const inserTemplate = async () => {
  //   const { data, error } = await supabase.from("email_template_table").insert([
  //     {
  //       template_name: formData.temp_name,
  //       subject_Line: formData.subject_line,
  //       description: formData.description,
  //       status, // formData.status,
  //       trigger: formData.triggers,
  //       email_Footer: formData.footer,
  //       from_Name: "NovaFarm Team",
  //       from_Email: "info@novapharm.io",
  //     },
  //   ]);
  //   if (error) {
  //     toast.error("Failed to create Template");
  //   } else {
  //     toast.success("Template created Successfully");
  //     fetchTemplates();
  //   }
  // };

  const inserTemplate = async () => {
    const payload = {
      template_name: formData.temp_name,
      subject_Line: formData.subject_line,
      description: formData.description,
      status,
      trigger: formData.triggers,
      email_Footer: formData.footer,
      from_Name: "NovaFarm Team",
      from_Email: "info@novapharm.io",
    };

    setIsLoading(true);
    try {
      if (selectedTemplate?.id) {
        // UPDATE existing
        const { error } = await supabase
          .from("email_template_table")
          .update(payload)
          .eq("id", selectedTemplate.id);

        if (error) throw error;
        toast.success("Template updated successfully");
      } else {
        // INSERT new
        const { error } = await supabase
          .from("email_template_table")
          .insert([payload]);

        if (error) throw error;
        toast.success("Template created successfully");
      }

      await fetchTemplates();
      setView("list");
    } catch (err) {
      console.error("Save template error:", err);
      toast.error(
        selectedTemplate?.id
          ? "Failed to update template"
          : "Failed to create template"
      );
    } finally {
      setIsLoading(false);
    }
  };

  const handleSaveTemplate = async () => {
    console.log("After Submit form Data is this : ", formData);
    inserTemplate();
  };

  const handleSendTest = () => {
    if (!testEmail) return;

    setIsLoading(true);
    // Simulate API call
    setTimeout(() => {
      setIsLoading(false);
      setShowTestModal(false);
      setTestEmail("");
      toast({
        title: "Test Email Sent",
        description: `Test email sent successfully to ${testEmail}`,
      });
    }, 2000);
  };

  const handleDeleteTemplate = async (templateId: string) => {
    if (window.confirm("Are you sure you want to delete this template?")) {
      setIsLoading(true);
      const { error } = await supabase
        .from("email_template_table")
        .delete()
        .eq("id", templateId);

      if (error) {
        console.error("Error deleting template:", error);
        toast("Error While Deleting");
      } else {
        toast("Template Deleted");
        await fetchTemplates();
      }
      setIsLoading(false);
    }
  };

  const formatDate = (timestamp) => {
    const date = new Date(timestamp);
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, "0");
    const day = String(date.getDate()).padStart(2, "0");
    const hours = String(date.getHours()).padStart(2, "0");
    const minutes = String(date.getMinutes()).padStart(2, "0");
    return `${year}-${month}-${day} ${hours}:${minutes}`;
  };

  const renderTemplateList = () => (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-gray-900 flex items-center gap-2">
            <Mail className="w-7 h-7 text-[#1C9B7A]" />
            Email Templates
          </h1>
          <p className="text-gray-600 mt-1">
            Manage and customize email templates for automated communications
          </p>
        </div>
        {/* <Button
          onClick={handleNewTemplate} 
          className="bg-[#27AE60] hover:bg-[#219A52]"
        >
          <Plus className="w-4 h-4 mr-2" />
          Add New Template
        </Button> */}
      </div>

      {/* Search and Filter */}
      <div className="flex flex-col sm:flex-row gap-4">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-4 h-4" />
          <Input
            placeholder="Search templates..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="pl-10"
          />
        </div>
        <div className="relative">
          <select
            value={filterStatus}
            onChange={(e) =>
              setFilterStatus(e.target.value as "all" | "active" | "inactive")
            }
            className="appearance-none bg-white border border-gray-300 rounded-md px-4 py-2 pr-8 focus:outline-none focus:ring-2 focus:ring-[#1C9B7A]"
          >
            <option value="all">All Status</option>
            <option value="active">Active</option>
            <option value="inactive">Inactive</option>
          </select>
          <ChevronDown className="absolute right-2 top-1/2 transform -translate-y-1/2 text-gray-400 w-4 h-4 pointer-events-none" />
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 gap-6">
        {loading ? (
          <div className="col-span-full text-center py-8 text-gray-600">
            <Spinner />
          </div>
        ) : filteredTemplates.length === 0 ? (
          <div className="col-span-full text-center py-12">
            <Mail className="w-12 h-12 text-gray-400 mx-auto mb-4" />
            <h3 className="text-lg font-medium text-gray-900 mb-2">
              No templates found
            </h3>
            <p className="text-gray-600 mb-4">
              Get started by creating your first email template.
            </p>
            <Button
              onClick={handleNewTemplate}
              className="bg-[#27AE60] hover:bg-[#219A52]"
            >
              <Plus className="w-4 h-4 mr-2" />
              Add New Template
            </Button>
          </div>
        ) : (
          filteredTemplates.map((template) => (
            <Card
              key={template.id}
              className="hover:shadow-lg transition-shadow"
            >
              <CardHeader className="pb-3">
                <div className="flex items-start justify-between">
                  <div className="flex-1">
                    <CardTitle className="text-lg text-left">
                      {template?.template_name}
                    </CardTitle>
                  </div>
                  <span
                    className={`px-2 py-1 rounded-full text-xs font-medium ${
                      template.status
                        ? "bg-green-100 text-green-800"
                        : "bg-gray-100 text-gray-800"
                    }`}
                  >
                    {template?.status ? "Active" : "In-Active"}
                  </span>
                </div>
              </CardHeader>
              <CardContent className="pt-0">
                <div className="space-y-2 text-sm text-gray-600 text-left">
                  <div>
                    <p>{template?.subject_Line}</p>
                  </div>
                  <div>
                    <strong>Type:</strong> {template?.trigger}
                  </div>
                  <div>
                    <strong>Last Modified:</strong>
                    {formatDate(template?.created_at)}
                  </div>
                </div>
                <div className="flex items-center gap-2 mt-4 flex-wrap">
                  <div className="flex items-center gap-2">
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => handleEditTemplate(template)}
                    >
                      <Edit3 className="w-3 h-3 mr-1" />
                      Edit
                    </Button>
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => {
                        setSelectedTemplate(template);
                        setView("preview");
                      }}
                    >
                      <Eye className="w-3 h-3 mr-1" />
                      Preview
                    </Button>
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => handleDeleteTemplate(template.id)}
                      className="text-red-600 hover:text-red-700 hover:border-red-300"
                    >
                      <Trash2 className="w-3 h-3" />
                    </Button>
                  </div>

                  {/* <div className="flex items-center">
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => handleDuplicateTemplate(template)}
                    >
                      <Copy className="w-3 h-3 mr-1" />
                      Duplicate
                    </Button>
                  </div> */}
                </div>
              </CardContent>
            </Card>
          ))
        )}
      </div>
    </div>
  );

  const renderEditor = () => (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <Button variant="ghost" onClick={() => setView("list")}>
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back to Templates
          </Button>
          <div>
            <h1 className="text-2xl font-bold text-gray-900">
              {selectedTemplate?.id &&
              dynamicTemplates.some((t) => t.id === selectedTemplate.id)
                ? "Edit Template"
                : "New Template"}
            </h1>
            {autoSaved && (
              <div className="flex items-center gap-2 text-sm text-green-600 mt-1">
                <Check className="w-4 h-4" />
                Auto-saved
              </div>
            )}
          </div>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="outline" onClick={() => setShowTestModal(true)}>
            <Send className="w-4 h-4 mr-2" />
            Send Test
          </Button>

          <Button
            onClick={() => {
              if (selectedTemplate) {
                setView("preview");
              }
            }}
            variant="outline"
          >
            <Eye className="w-4 h-4 mr-2" />
            Preview
          </Button>
          <Button
            onClick={handleSaveTemplate}
            disabled={isLoading}
            className="bg-[#27AE60] hover:bg-[#219A52]"
          >
            {isLoading ? "Saving..." : "Save Template"}
          </Button>
        </div>
      </div>

      {/* Editor Form */}
      <div className="grid grid-cols-1 lg:grid-cols-1 gap-8">
        <div className="space-y-6 text-left">
          <Card>
            <CardHeader>
              <CardTitle>Template Details</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <label
                  className="block text-sm font-medium mb-2"
                  htmlFor="temp_name"
                >
                  Template Name
                </label>
                <Input
                  name="temp_name"
                  value={formData.temp_name}
                  onChange={handleInputChange}
                  placeholder="Enter template name"
                />
              </div>

              <div>
                <label
                  className="block text-sm font-medium mb-2"
                  htmlFor="subject_line"
                >
                  Subject Line
                </label>
                <Input
                  name="subject_line"
                  value={formData.subject_line}
                  onChange={handleInputChange}
                  placeholder="Email subject line"
                />
              </div>

              <div className="h-[200px]">
                <label
                  className="block text-sm font-medium mb-2"
                  htmlFor="description"
                >
                  Description
                </label>

                <ReactQuill
                  className="h-[130px]"
                  theme="snow"
                  value={editorContent}
                  onChange={(value) => {
                    setEditorContent(value);
                    setFormData((prev) => ({ ...prev, description: value }));
                  }}
                  placeholder="Start typing here..."
                />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label
                    className="block text-sm font-medium mb-2"
                    htmlFor="status"
                  >
                    Status
                  </label>
                  <select
                    name="status"
                    value={status ? "Active" : "Inactive"}
                    onChange={(e) => setStatus(e.target.value === "Active")}
                    className="w-full border border-gray-300 rounded-md px-3 py-2 focus:outline-none focus:ring-2 focus:ring-[#1C9B7A]"
                  >
                    <option value="Active">Active</option>
                    <option value="Inactive">Inactive</option>
                  </select>
                </div>
                <div>
                  <label
                    className="block text-sm font-medium mb-2"
                    htmlFor="triggers"
                  >
                    Trigger
                  </label>
                  <select
                    className="w-full border border-gray-300 rounded-md px-3 py-2 focus:outline-none focus:ring-2 focus:ring-[#1C9B7A]"
                    // value={selectedTrigger}
                    value={formData.newTrigger}
                    onChange={(e) => {
                      setSelectedTrigger(e.target.value);
                      setFormData((prev) => ({
                        ...prev,
                        triggers: e.target.value,
                      }));
                    }}
                  >
                    {AllTriggers.map((singleTrigger) => (
                      <option
                        key={singleTrigger.id}
                        value={singleTrigger.trigger_name}
                      >
                        {singleTrigger.trigger_name}
                      </option>
                    ))}
                  </select>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );

  const renderPreview = () => {
    const getPreviewContent = (content: string) => {
      if (!content) return "";

      return content
        .replace(/\{\{client_name\}\}/g, "John Doe")
        .replace(/\{\{invoice_total\}\}/g, "$99.00")
        .replace(/\{\{invoice_number\}\}/g, "INV-2024-001")
        .replace(/\{\{company_name\}\}/g, "NovaFarm")
        .replace(/\{\{date\}\}/g, new Date().toLocaleDateString());
    };

    return (
      <div className="space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Button
              variant="ghost"
              onClick={() =>
                setView(
                  selectedTemplate?.id &&
                    dynamicTemplates.some((t) => t.id === selectedTemplate.id)
                    ? "list"
                    : "list"
                )
              }
            >
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back
            </Button>
            <h1 className="text-2xl font-bold text-gray-900">
              Preview: {selectedTemplate?.template_name}
            </h1>
          </div>
          <div className="flex items-center gap-2">
            <Button
              variant={previewMode === "desktop" ? "default" : "outline"}
              size="sm"
              onClick={() => setPreviewMode("desktop")}
            >
              <Monitor className="w-4 h-4 mr-2" />
              Desktop
            </Button>
            <Button
              variant={previewMode === "mobile" ? "default" : "outline"}
              size="sm"
              onClick={() => setPreviewMode("mobile")}
            >
              <Smartphone className="w-4 h-4 mr-2" />
              Mobile
            </Button>
          </div>
        </div>

        {/* Preview */}
        <div className="flex justify-center ">
          <div
            className={`bg-white border border-gray-300 rounded-lg shadow-lg ${
              previewMode === "mobile" ? "max-w-sm" : "max-w-2xl w-full"
            }`}
          >
            {/* Email Header */}
            <div className="border-b border-gray-200 p-4 bg-gray-50">
              <div className="text-sm text-gray-600 space-y-1 text-left">
                <div>
                  <strong>From:</strong> {selectedTemplate?.from_Name} &lt;
                  {selectedTemplate?.from_Email}&gt;
                </div>

                <div>
                  <strong>Subject:</strong>{" "}
                  {getPreviewContent(selectedTemplate?.subject_Line || "")}
                </div>
                <div>
                  <strong>Reply-To:</strong>
                  {selectedTemplate?.reply_to_email}
                </div>
              </div>
            </div>

            {/* Footer */}
            <div className="p-4 text-left">
              {/* <div>{selectedTemplate?.description}</div> */}
              <div
                dangerouslySetInnerHTML={{
                  __html: selectedTemplate?.description || "",
                }}
              />

              {selectedTemplate?.email_Footer && (
                <div className="mt-8 pt-4 border-t border-gray-200">
                  <div
                    dangerouslySetInnerHTML={{
                      __html: getPreviewContent(selectedTemplate.email_Footer),
                    }}
                    className="text-xs text-gray-500"
                  />
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    );
  };

  const emailwithTemplate = async () => {
    const {
      data: { session },
    } = await supabase.auth.getSession();

    const accessToken = session?.access_token;

    const res = await fetch(
      "https://ajbxscredobhqfksaqrk.supabase.co/functions/v1/email-with-template",
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${accessToken}`,
        },
        body: JSON.stringify({
          to: "fakharali054@gmail.com",
          subject: "Welcome! 🎉",
          templateName: "emailFile",
          data: {
            title: "Welcome!",
            username: "Fakhir",
            bodyText: "Thanks for joining. We're glad to have you!",
            footerText: "© 2025 Your Company. All rights reserved.",
          },
        }),
      }
    );
    const text = await res.text();
    if (!res.ok) {
      console.error("Function error:", res.status, text);
    } else {
      console.log("Function success:", text);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50">
      {view === "list" && renderTemplateList()}
      {view === "editor" && renderEditor()}
      {view === "preview" && renderPreview()}

      {/* Test Email Modal */}
      {showTestModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-lg max-w-md w-full p-6">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-lg font-semibold">Send Test Email</h3>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => setShowTestModal(false)}
              >
                <X className="w-4 h-4" />
              </Button>
            </div>

            <div className="space-y-4">
              <div>
                <label
                  htmlFor="testEmail"
                  className="block text-sm font-medium mb-2"
                >
                  Recipient Email
                </label>
                <Input
                  id="testEmail"
                  type="email"
                  value={testEmail}
                  onChange={(e) => setTestEmail(e.target.value)}
                  placeholder="test@example.com"
                />
              </div>
              <div className="flex justify-end gap-2">
                <Button
                  variant="outline"
                  onClick={() => setShowTestModal(false)}
                >
                  Cancel
                </Button>
                <Button onClick={handleSendTest} disabled={isLoading}>
                  {isLoading ? "Sending..." : "Send"}
                </Button>
              </div>
              {isLoading && (
                <div className="flex items-center justify-center gap-2 text-sm text-gray-500">
                  <AlertCircle className="w-4 h-4" /> Sending test email...
                </div>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
